### ISSUE TITLE
problem installing speckle-blender

### ISSUE THREAD

**Issue by PavlosDem99** [specklesystems/speckle-blender#168]
I can't install the speckle-blender (Blender version 3.6 and speckle-blender 2.15)

This is the log message that appears during the installation. I followed the guidance in the website
https://speckle.systems/tutorials/getting-started-with-speckle-for-blender/

log message

Read prefs: "C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
DEBUG:BlenderGIS-228.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-228.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-228.core.checkdeps:Pillow unavailable
DEBUG:BlenderGIS-228.core.checkdeps:ImageIO Freeimage plugin available
INFO:xmlschema:Resource 'XMLSchema.xsd' is already loaded
Starting module dependency installation
C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\bin\python.exe
C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Using connector installation path C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6
Installing Speckle dependencies to C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6
Successfully found dependencies
Traceback (most recent call last):
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\requests_toolbelt\_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\urllib3\contrib\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\bpy_speckle\__init__.py", line 10, in <module>
    from bpy_speckle.operators import *
  File "C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\bpy_speckle\operators\__init__.py", line 1, in <module>
    from .users import LoadUsers, LoadUserStreams, ResetUsers
  File "C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\bpy_speckle\operators\users.py", line 8, in <module>
    from bpy_speckle.clients import speckle_clients
  File "C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\bpy_speckle\clients.py", line 4, in <module>
    from specklepy.api.client import SpeckleClient
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\specklepy\api\client.py", line 8, in <module>
    from gql.transport.requests import RequestsHTTPTransport
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\gql\transport\requests.py", line 11, in <module>
    from requests_toolbelt.multipart.encoder import MultipartEncoder
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\requests_toolbelt\__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\requests_toolbelt\adapters\__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\requests_toolbelt\adapters\ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\requests_toolbelt\_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\urllib3\contrib\__init__.py)

Using connector installation path C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6
Installing Speckle dependencies to C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6
Successfully found dependencies
Traceback (most recent call last):
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\requests_toolbelt\_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\urllib3\contrib\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\bpy_speckle\__init__.py", line 10, in <module>
    from bpy_speckle.operators import *
  File "C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\bpy_speckle\operators\__init__.py", line 1, in <module>
    from .users import LoadUsers, LoadUserStreams, ResetUsers
  File "C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\bpy_speckle\operators\users.py", line 8, in <module>
    from bpy_speckle.clients import speckle_clients
  File "C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\bpy_speckle\clients.py", line 4, in <module>
    from specklepy.api.client import SpeckleClient
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\specklepy\api\client.py", line 8, in <module>
    from gql.transport.requests import RequestsHTTPTransport
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\gql\transport\requests.py", line 11, in <module>
    from requests_toolbelt.multipart.encoder import MultipartEncoder
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\requests_toolbelt\__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\requests_toolbelt\adapters\__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\requests_toolbelt\adapters\ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "C:\Users\pavlo\AppData\Roaming\Speckle\connector_installations\Blender 3.6\requests_toolbelt\_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\urllib3\contrib\__init__.py)

**Comment by JR-Morgan** [comment]
Hey @PavlosDem99

Please can you let us know what other blender plugins you have installed.

Some [other users were noticing some similar problem](https://speckle.community/t/speckle-blender-connection/7034/6), and a reinstall of both the BlenderBim and Speckle plugins were able to solve their issue.

Please could you try the above and let us know if this resolves your issue.

**Comment by JR-Morgan** [comment]
Hi @PavlosDem99

Any updates? Are you still having problems?

I will close this issue for now. If you're still having issues we can re-open.
