### ISSUE TITLE
Plugin activation error due to `typing_extensions`

### ISSUE THREAD

**Issue by TZwielehner** [specklesystems/speckle-blender#67]
I installed the addin (2.2.3) for blender 2.93 via the speckle manager application (v2.1.11).

### Expected vs. Actual Behavior

 When I try to activate it, I get the following error:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\ABC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\bpy_speckle\__init__.py", line 56, in <module>
    from specklepy.api.client import SpeckleClient  # , SpeckleCache
  File "C:\Users\ABC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modules\specklepy\api\client.py", line 6, in <module>
    from specklepy.api import resources
  File "C:\Users\ABC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modules\specklepy\api\resources\__init__.py", line 10, in <module>
    imported_module = import_module("." + name, package=__name__)
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\ABC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modules\specklepy\api\resources\branch.py", line 1, in <module>
    from specklepy.api.resources import stream
  File "C:\Users\ABC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modules\specklepy\api\resources\stream.py", line 3, in <module>
    from specklepy.logging import metrics
  File "C:\Users\ABC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modules\specklepy\logging\metrics.py", line 7, in <module>
    from specklepy.transports.sqlite import SQLiteTransport
  File "C:\Users\ABC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modules\specklepy\transports\sqlite.py", line 9, in <module>
    from specklepy.transports.abstract_transport import AbstractTransport
  File "C:\Users\ABC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modules\specklepy\transports\abstract_transport.py", line 3, in <module>
    from pydantic import BaseModel
  File "pydantic\__init__.py", line 2, in init pydantic.__init__
  File "pydantic\dataclasses.py", line 3, in init pydantic.dataclasses
  File "pydantic\class_validators.py", line 8, in init pydantic.class_validators
  File "pydantic\errors.py", line 5, in init pydantic.errors
  File "pydantic\typing.py", line 23, in init pydantic.typing
  File "C:\Users\ABC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modules\typing_extensions.py", line 1493, in <module>
    def TypeAlias(self, parameters):
TypeError: __init__() missing 1 required positional argument: 'doc'
```

### Reproduction Steps & System Config (win, osx, web, etc.)

Windows 10

**Comment by izzylys** [comment]
Heya!

I've not seen this error before so I'm not sure what could be causing it, but it looks like it's somehow an issue with with `typing_extensions` and not `specklepy` or `speckle-blender`.

Do you have any other Blender addons installed that could be conflicting? If you can safely delete the `...\Blender\2.93\scripts\addons` folder, give that a try and then uninstall / reinstall `speckle-blender`. 

Could you also let me know what your blender's python version is? You can find this by heading to `C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin` and double clicking the python executable. It should open a terminal which will show you what version you're on.

**Comment by TZwielehner** [comment]
Hi!
Python version is 3.9.2. I have a few other addons installed. I deactivated all other addins, but I still get the error. I'll check the delete option and will report again.

**Comment by TZwielehner** [comment]
I deleted the content of the addons folder and reinstalled the speckle addin, still the same error.

**Comment by izzylys** [comment]
Hi, this is very strange!

As another check, could you please let me know what version of `pydantic` and `typing_extensions` you have in your `addons\modules` folder? It should be `pydantic-1.8.2` and `typing_extensions-4.0.0`.

I will also have a look to see if there are any dependencies I can update in `specklepy` to push a new release of `speckle-blender`.

**Comment by TZwielehner** [comment]
Pydantic is 1.8.2, typing extension is 4.0.0. However, I only have a `typing_extension-4.0.0.dist-info` folder and no typing_extension folder; is that a problem maybe?

**Comment by izzylys** [comment]
Ok thanks for the info! Yes, `typing_extensions` will just be a file, not a folder. I will have a look to see if there's anything I can upgrade or change in the dependencies and get back to you.

Out of curiosity, is anyone else you're working with having this issue or is it just happening on your machine? If others are also experiencing it, is it with the same environment (eg blender 2.93, windows 10, speckle-blender 2.2.3/4)?

**Comment by TZwielehner** [comment]
I'm just testing it myself, I'll check if I find someone to try it, too; maybe I'll find another machine and check if the problem persists.

**Comment by izzylys** [comment]
heya!

v2.2.5 is building as we speak, so it should soon be available to install via Speckle Manager. what I've done is upgrade a few things in `specklepy` to see if this resolves the issue. I'm not confident that it will, but it's worth a shot I think to at least rule that out.

please let me know if anything is different after the upgrade!

**Comment by izzylys** [comment]
hiya!

quick update: v2.2.7 completely changes the install process and hopefully removes any discrepancies in the install process from person to person. the bug you were having here is still quite mysterious to me, but may still be resolved by this new update. if you have a chance to test it, I would love to know if it works out for you 😊
